matcher:
  KDTreeMatcher:
    knn: 15
    maxDist: 2.0
    epsilon: 1

outlierFilters:
 - TrimmedDistOutlierFilter:
    ratio: 0.7

errorMinimizer:
  PointToPlaneWithAltitudeErrorMinimizer:
         force4DOF: 1
         forceAltitude: 1

transformationCheckers:
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001
      minDiffTransErr: 0.01
      smoothLength: 2
  - CounterTransformationChecker:
      maxIterationCount: 40
  - BoundTransformationChecker:
      maxRotationNorm: 6.1
      maxTranslationNorm: 5.00

inspector:
  NullInspector

logger:
  NullLogger

